name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
        with:
          node-version: 20
          package-manager: npm@latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
